name: RyanEliDiego.ai
favicon: null
layout_spectrum: 0.31841
typography_spectrum: 0.50511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a39'
    - '#afada0'
    - '#928f88'
    - '#785e62'
    - '#1a394b'
  brandStrength: 0.875
  lightness: 0.6676303746644408
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
